baseURL = 'https://ayushlikestodev.web.app/'
languageCode = 'en-us'
title = 'Ayush Likes To Dev'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false # Important; this allows us to use custom CSS for syntax highlighting
    noHl = false
    style = 'monokai'
    tabWidth = 4
